### PR TITLE
Added Zangief.  Improved SpritePathService

### PR DESCRIPTION
**Pull request by dylanthompson**
Trying JSON to Typescript

### CODE REVIEW

**Review by troyrthompson — CHANGES_REQUESTED** [review]
:+1: the sprite data being passed through getStateSpritePaths to animate is neat

I was getting an error, looks like the silsam data should be updated?

**Comment by dylanthompson** [comment]
Yes, I see.  I can update the sprite.json file for silsam

**Review by troyrthompson — APPROVED** [review]
Noice

**Comment by dylanthompson** [comment]
YAHOO.  I also found a new feature of the game.  The left and right arrow keys can be used to move both characters by way of a horizontal scroll bar on the body.

**Comment by troyrthompson** [comment]
nice all horizontal animation can be handled natively by the browser :hand: #optimized

**Comment by dylanthompson** [comment]
Those were my thoughts exactly.  Also jump, double/triple/n-ple jump, super jump, and fly mode is implemented per vertical scroll bar.

**Pull request merged**
